"""Added some fields in User Table

Revision ID: 906fdefef79f
Revises: 45c248e612eb
Create Date: 2023-11-02 13:19:36.514163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906fdefef79f'
down_revision: Union[str, None] = '45c248e612eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Address', ['address_id'])
    op.add_column('users', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'Address', type_='unique')
    # ### end Alembic commands ###
