"""Added KeyCloakId in User Table

Revision ID: 9bba91c4c0e2
Revises: 906fdefef79f
Create Date: 2023-11-02 16:11:20.547468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bba91c4c0e2'
down_revision: Union[str, None] = '906fdefef79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keycloak_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'keycloak_id')
    # ### end Alembic commands ###
